version: 2
jobs:
  test:
     docker:
       - image: circleci/golang:1.15
     steps:
       - checkout

       - run:
           name: Run unit tests
           command: |
             go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

       - run:
           name: Upload codecov report
           command: |
             bash <(curl -s https://codecov.io/bash)

  lint:
     docker:
       - image: circleci/golang:1.15
     steps:
       - checkout

       - run:
           name: Install golangci-lint
           command: |
             curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2

       - run:
           name: Run golangci-lint
           command: |
             golangci-lint run -v ./...

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
      - lint
